---
name: ci

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/common.txt') }}-${{ hashFiles('requirements/dev.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install test dependencies
        run: |
          pip3 install -r requirements/common.txt
          pip3 install -r requirements/test.txt
