---
name: ci

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create or restore virtualenv
        uses: syphar/restore-virtualenv@v1.2
        id: cache-venv
        with:
          requirement_files: |
            requirements/common.txt
            requirements/dev.txt

      - name: Restore pip cache
        if: steps.cache-venv.outputs.cache-hit != 'true'
        uses: syphar/restore-pip-download-cache@v1
        with:
          requirement_files: |
            requirements/common.txt
            requirements/dev.txt

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          pip3 install -r requirements/common.txt
          pip3 install -r requirements/dev.txt

      - name: YAML lint
        run: yamllint .
